export enum EIcon {
  editGrid = 'feather-edit',
  deleteGrid = 'feather-trash-2',
  checkSelection = 'feather-check-square',
  attendGrid = 'fa fa-hand-pointer',
  saveGrid = 'feather-save',
  cancel = 'feather-x',
  retweet = 'fa fa-retweet',
  copy = 'feather-copy',
  show = 'fa fa-eye',
  overview = 'feather-eye',
  overviewOff ='feather-eye-off',
  folder = 'feather-folder',
  include = 'feather-file-plus',
  plusGrid = 'feather-plus',
  plusCircle = 'feather-plus-circle',
  showGrid = 'feather-eye',
  rejectRequest ='fa fa-times-circle',
  createQuoterOrder ='fa fa-plus-square',
  bookMark ='feather-bookmark',
  clipBoard ='feather-clipboard',
  fileText ='feather-file-text',
  compass ='feather-compass',
  list ='feather-list',
  notification ='feather-bell',
  up='feather-arrow-up',
  down='feather-arrow-down',
  userCheck='feather-user-check',
  userX='feather-user-x',
  user='feather-user',
  send ='feather-send',
  check = 'feather-check',
  filetText = 'feather-file-text',
  square = 'feather-square',
  logOut ='feather-log-out',
  download = 'feather-download',
  settings = 'feather-settings',
  repeat = 'feather-repeat',
  box = '-box',
  detail = 'feather-align-left',


}

